################################################################################
#
#  This file is part of SplashSync Project.
# 
#  Copyright (C) Splash Sync <www.splashsync.com>
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
# 
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Docker Compose File
#
# This Docker File intend to Create a Complete Dev Envirenement 
# for Splash Modules on Prestashop
#
# To us different PS Version coinfigured, you need to add hosts to /etc/hosts
# 
# 172.169.2.10    	    py.splashsync.local
#
################################################################################


version: '2'

services:

    ################################################################################
    # Python 3.9 - Splash Py
    splashpy-3.9:
        build:
            context: ./
            dockerfile: docker/Dockerfile
            args:
                image:  python:3.9-slim
        container_name: 3p9.splashpy.local
        volumes:
            # Server Sources in Read Only Mode
            - "./:/app/"
            - "./splashpy:/app/splashpy:ro"
        hostname: 3p9.splashpy.local
        networks:
            pycore:         { ipv4_address: 172.169.2.39, aliases: [ 3p9.splashpy.local ] }
            splashsync:     { aliases: [ 3p9.splashpy.local ] }

    ################################################################################
    # Python 3.8 - Splash Py
    splashpy-3.8:
        build:
            context: ./
            dockerfile: docker/Dockerfile
            args:
                image:  python:3.8-slim
        container_name: 3p8.splashpy.local
        volumes:
            # Server Sources in Read Only Mode
            - "./:/app/"
            - "./splashpy:/app/splashpy:ro"
        hostname: 3p8.splashpy.local
        networks:
            pycore:         { ipv4_address: 172.169.2.38, aliases: [ 3p8.splashpy.local ] }
            splashsync:     { aliases: [ 3p8.splashpy.local ] }

    ################################################################################
    # Python 3.7 - Splash Py
    splashpy-3.7:
        build:
            context: ./
            dockerfile: docker/Dockerfile
        container_name: 3p7.splashpy.local
        volumes:
            # Server Sources in Read Only Mode
            - "./:/app/"
            - "./splashpy:/app/splashpy:ro"
        hostname: 3p7.splashpy.local
        networks:
            pycore:         { ipv4_address: 172.169.2.37, aliases: [ 3p7.splashpy.local ] }
            splashsync:     { aliases: [ 3p7.splashpy.local ] }

    ################################################################################
    # Splash Toolkit Container
    toolkit:
        image:              'splashsync/toolkit'
        container_name:     toolkit.splashpy.local
        volumes:
            # Specify Local Configuration File
            - './docker/toolkit/splash.yml:/app/config/packages/splash.yml:ro'
        hostname:           toolkit.splashpy.local
        networks:
            pycore:         { ipv4_address: 172.169.2.10, aliases: [ toolkit.splashpy.local ] }
            splashsync:     { aliases: [ toolkit.splashpy.local ] }
            
networks:
    ################################################################################
    # Default Private Network    
    pycore:
        driver: bridge
        ipam:
            config:
                - subnet: 172.169.2.0/24
    ################################################################################
    # External Splash Network
    splashsync:
        external: true