################################################################################
#
#  This file is part of SplashSync Project.
# 
#  Copyright (C) Splash Sync <www.splashsync.com>
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
# 
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Docker Compose File
#
# This Docker File intend to Create a Complete Dev Envirenement 
# for Splash Modules on Prestashop
#
# To us different PS Version coinfigured, you need to add hosts to /etc/hosts
# 
# 172.169.2.10    	    py.splashsync.local
#
################################################################################


version: '2'

services:

    ################################################################################
    # Splash Py Container
    splash:
        build:
            context: ./
            dockerfile: docker/Dockerfile
        container_name: py-splashsync
        tty: true
        volumes:
            # Server Sources in Read Only Mode
            - "./:/app/"
            - "./splashpy:/app/splashpy:ro"
        hostname: py-server.splashsync.local
        networks:
            pycore:         { ipv4_address: 172.169.2.11, aliases: [ py-server.splashsync.local ] }
            splashsync:     { aliases: [ py-server.splashsync.local ] }

    ################################################################################
    # Splash Toolkit Container
    toolkit:
        image: 'splashsync/toolkit'
        container_name: py-toolkit
        volumes:
            # Specify Local Configuration File
            - './docker/toolkit/splash.yml:/app/config/packages/splash.yml:ro'
        hostname:           py.splashsync.local
        networks:
            pycore:         { ipv4_address: 172.169.2.10, aliases: [ py.splashsync.local ] }
            splashsync:     { aliases: [ py.splashsync.local ] }
            
networks:
    ################################################################################
    # Default Private Network    
    pycore:
        driver: bridge
        ipam:
            config:
                - subnet: 172.169.2.0/24
    ################################################################################
    # External Splash Network
    splashsync:
        external: true